const ADD_TODO = 'ADD_TODO'
const CHANGE_TODO_DONE = 'CHANGE_TODO_DONE'
const DEL_TODO = 'DEL_TODO'
const CHANGE_ALL_DONE = 'CHANGE_ALL_DONE'
const DEL_COMPLETE_TODOS = 'DEL_COMPLETE_TODOS'

export {
  ADD_TODO,
  CHANGE_ALL_DONE,
  CHANGE_TODO_DONE,
  DEL_TODO,
  DEL_COMPLETE_TODOS
}